#!/bin/bash

selected=`cat ~/.cht-langs ~/.cht-utils | fzf`
if [[ -z $selected ]]; then
    exit 0
fi

read -p "Query: " query

if grep -qs "$selected" ~/.cht-langs; then
    query=`echo $query | tr ' ' '+'`
    tmux neww bash -c "echo \"curl cht.sh/$selected/$query/\" & curl cht.sh/$selected/$query & read"
else
    tmux neww bash -c "curl -s cht.sh/$selected~$query | less"
fi
