#!/bin/bash

#where to look for projects
PROJECTS=$HOME/sources

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find $PROJECTS -maxdepth 5 -name ".git" -type d -exec dirname {} \; | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_config="$selected/.tmux.yml"

if [ -f "$tmux_config" ]; then
    tmuxinator start -p "$tmux_config"
    exit 0
fi

tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
